RELATIVE_STRENGTH_PERIOD = 126

FIFTY_TWO_WEEK_PERIOD = 252

EMA_FAST = 20
EMA_MEDIUM = 50
EMA_SLOW = 200

VOLUME_SMA_PERIOD = 20

FIFTY_TWO_WEEK_THRESHOLD = 0.95

MIN_CANDLES_REQUIRED = 252

CUP_HANDLE_PIVOT_LOOKBACK = 3
CUP_HANDLE_PIVOT_THRESHOLD = 0.02
CUP_HANDLE_MIN_PRIOR_TREND_DAYS = 20
CUP_HANDLE_MIN_PRIOR_TREND_GAIN = 0.10
CUP_HANDLE_DEPTH_MIN = 0.12
CUP_HANDLE_DEPTH_MAX = 0.35
CUP_HANDLE_MIN_DURATION = 20
CUP_HANDLE_MAX_DURATION = 90
CUP_HANDLE_MAX_RIM_DIFF = 0.07
CUP_HANDLE_BOTTOM_POSITION_MIN = 0.30
CUP_HANDLE_BOTTOM_POSITION_MAX = 0.70
CUP_HANDLE_NEAR_BOTTOM_THRESHOLD = 0.08
CUP_HANDLE_MIN_NEAR_BOTTOM_BARS = 3
CUP_HANDLE_RIGHT_RECOVERY_MIN = 0.92

CUP_HANDLE_HANDLE_MIN_BARS = 3
CUP_HANDLE_HANDLE_MAX_DURATION = 15
CUP_HANDLE_HANDLE_MAX_DEPTH = 0.12
CUP_HANDLE_HANDLE_MAX_RANGE = 0.10

TREND_TEMPLATE_MAX_DISTANCE_FROM_HIGH = 0.75