RELATIVE_STRENGTH_PERIOD = 126

FIFTY_TWO_WEEK_PERIOD = 252

EMA_FAST = 20
EMA_MEDIUM = 50
EMA_SLOW = 200

VOLUME_SMA_PERIOD = 20

FIFTY_TWO_WEEK_THRESHOLD = 0.95

MIN_CANDLES_REQUIRED = 252

CUP_HANDLE_PIVOT_LOOKBACK = 3
CUP_HANDLE_PIVOT_THRESHOLD = 0.02
CUP_HANDLE_MIN_PRIOR_TREND_DAYS = 20
CUP_HANDLE_MIN_PRIOR_TREND_GAIN = 0.10
CUP_HANDLE_DEPTH_MIN = 0.12
CUP_HANDLE_DEPTH_MAX = 0.35
CUP_HANDLE_MIN_DURATION = 20
CUP_HANDLE_MAX_DURATION = 90
CUP_HANDLE_MAX_RIM_DIFF = 0.07
CUP_HANDLE_BOTTOM_POSITION_MIN = 0.30
CUP_HANDLE_BOTTOM_POSITION_MAX = 0.70
CUP_HANDLE_NEAR_BOTTOM_THRESHOLD = 0.08
CUP_HANDLE_MIN_NEAR_BOTTOM_BARS = 3
CUP_HANDLE_RIGHT_RECOVERY_MIN = 0.92
# 350
CUP_HANDLE_SEARCH_WINDOW = 600 
CUP_HANDLE_MAX_PATTERN_AGE = 20
CUP_HANDLE_MAX_BREAKOUT_AGE = 5
CUP_HANDLE_HANDLE_LOOKBACK = 30

CUP_HANDLE_HANDLE_MIN_BARS = 3
CUP_HANDLE_HANDLE_MAX_DURATION = 15
CUP_HANDLE_HANDLE_MAX_DEPTH = 0.12
CUP_HANDLE_HANDLE_MAX_RANGE = 0.10

TREND_TEMPLATE_MAX_DISTANCE_FROM_HIGH = 0.75

VCP_SEARCH_WINDOW = 600
VCP_MIN_CONTRACTION_LEGS = 1
VCP_MIN_PIVOT_COUNT = 5
VCP_MIN_LEG_PERCENT = 0.05
VCP_MAX_LEG_PERCENT = 0.45
VCP_CONTRACTION_DECREASE_RATIO = 1.10
VCP_HIGH_TIGHTENING_TOLERANCE = 0.03
VCP_LOW_TIGHTENING_TOLERANCE = 0.03
VCP_VOLUME_CONTRACTION_TOLERANCE = 0.05
VCP_BREAKOUT_PROXIMITY = 0.03
VCP_MAX_PATTERN_AGE = 20
VCP_MAX_BREAKOUT_AGE = 5
MAX_RECENT_PIVOTS = 12
MIN_SEQUENCE_LENGTH = 5