"""Create OHLCV table

Revision ID: 6c1426fb8614
Revises: d4e9116391aa
Create Date: 2026-07-08 14:08:46.146348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c1426fb8614'
down_revision: Union[str, Sequence[str], None] = 'd4e9116391aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ohlcv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('high', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('low', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('close', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('volume', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'timeframe', 'timestamp', name='uq_ohlcv_candle')
    )
    op.create_index('idx_ohlcv_lookup', 'ohlcv', ['instrument_id', 'timeframe', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ohlcv_lookup', table_name='ohlcv')
    op.drop_table('ohlcv')
    # ### end Alembic commands ###
