"""Add instrument metadata

Revision ID: 80ebfb194b00
Revises: d26f0de15f89
Create Date: 2026-07-12 10:30:38.677863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80ebfb194b00'
down_revision: Union[str, Sequence[str], None] = 'd26f0de15f89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instruments', sa.Column('exchange', sa.String(length=20), nullable=True))
    op.add_column('instruments', sa.Column('name', sa.String(length=100), nullable=True))
    op.add_column('instruments', sa.Column('sector', sa.String(length=100), nullable=True))
    op.add_column('instruments', sa.Column('industry', sa.String(length=100), nullable=True))
    op.drop_index(op.f('idx_watchlist_item_instrument'), table_name='watchlist_items')
    op.drop_index(op.f('idx_watchlist_item_watchlist'), table_name='watchlist_items')
    op.drop_constraint(op.f('uq_watchlist_item'), 'watchlist_items', type_='unique')
    op.drop_index(op.f('idx_watchlist_name'), table_name='watchlists')
    op.drop_constraint(op.f('watchlists_name_key'), 'watchlists', type_='unique')
    op.create_index(op.f('ix_watchlists_name'), 'watchlists', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlists_name'), table_name='watchlists')
    op.create_unique_constraint(op.f('watchlists_name_key'), 'watchlists', ['name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_watchlist_name'), 'watchlists', ['name'], unique=False)
    op.create_unique_constraint(op.f('uq_watchlist_item'), 'watchlist_items', ['watchlist_id', 'instrument_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_watchlist_item_watchlist'), 'watchlist_items', ['watchlist_id'], unique=False)
    op.create_index(op.f('idx_watchlist_item_instrument'), 'watchlist_items', ['instrument_id'], unique=False)
    op.drop_column('instruments', 'industry')
    op.drop_column('instruments', 'sector')
    op.drop_column('instruments', 'name')
    op.drop_column('instruments', 'exchange')
    # ### end Alembic commands ###
